<div class="search top"><?= $this->search ?>
    <div class="total"><?= $this->pagination()->getPager()->getNumResults() ?> registro(s) encontrado(s).</div>
</div>

<?= $this->flash()->render() ?>



<?= $this->pagination()->render() ?>
<table class="crud">
    <tr>
        <th>Foto</th>
        <th>Modelo</th>
        <th>Cor</th>
        <th>Ano/Mod</th>
        <th>Valor</th>
        <th>Marca</th>
        <th>Placa</th>
        <th>Situação</th>


        <th><a class="new-register" href="<?= $this->url(array(
            'module'=>'admin',
            'controller' => 'vehicle',
            'action' => 'add'
        ),null,true)?>" >Adicionar</a></th>

    </tr>
    <? foreach($this->registers as $i => $register) : ?>
        <tr class="r<?=($i%2)?>">
            <td class="thumb">

            <?php
                $image = $register->getImage();
            ?>
                <? if ($image) : ?>
                    <img src="<?= $this->image($image->Image->filename . '.png', '100x100') ?>"
                         alt="<?= $image->alt ?>" title="<?= $image->title ?>" />
                <? else: ?>
                    Sem imagem.
                <? endif; ?>
            

            </td>


            <td><?= $register->model ?></td>
            <td><?= $register->color ?></td>
            <td class="right"><?= $register->year ?>/<?= $register->modelYear ?></td>
            <td class="right"><?= $register->price ?></td>
            <td><?= $register->Brand->name ?></td>
            <td class="right"><?= $register->licensePlate ?></td>
            <td>
                <div class="status-<?= $register->status_id ?>" >
                </div>
                <?= $register->Status->name ?>
            </td>


            <td class="actions">
                <a class="edit" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'vehicle',
                            'action' => 'view',
                            'id' => $register->id
                        ),null,true)?>" >Visualizar</a>
                <br />
                <a class="edit" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'vehicle',
                            'action' => 'edit',
                            'id' => $register->id
                        ),null,true)?>" >Editar</a>
                <br />
                <a class="del" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'vehicle',
                            'action' => 'del',
                            'id' => $register->id
                        ),null,true)?>" >Excluir</a>
            </td>
        </tr>

    <? endforeach ?>

</table>
<?= $this->pagination()->render() ?>
