
<div class="search top"><?= $this->search?></div>
<? include '_submenu.phtml' ?>


<?php $vehicle = $this->register ?>


<table class="crud">
    <tr>
        <th colspan="2">Principal</th>
    </tr>
    <tr>
        <th class="title">Marca</th>
        <td><?= $vehicle->Brand->name ?></td>
    </tr>
    <tr>
        <th class="title">Modelo</th>
        <td><?= $vehicle->model ?></td>
    </tr>
    <tr>
        <th class="title">Placa</th>
        <td><?= $vehicle->licensePlate ?></td>
    </tr>
    <tr>
        <th class="title">Cor</th>
        <td><?= $vehicle->color ?></td>
    </tr>
    <tr>
        <th class="title">Ano</th>
        <td><?= $vehicle->year ?></td>
    </tr>
    <tr>
        <th class="title">Ano Modelo</th>
        <td><?= $vehicle->modelYear ?></td>
    </tr>
    <tr>
        <th class="title">Valor</th>
        <td><?= $vehicle->price ?></td>
    </tr>
    <tr>
        <th class="title">Exibir valor</th>
        <td><?= ($vehicle->showPrice) ? 'Sim' : 'Não' ?></td>
    </tr>
    <tr>
        <th class="title">Situação</th>
        <td><?= $vehicle->Status->name ?></td>
    </tr>
    <tr>
        <th class="title">Ordem</th>
        <td><?= $vehicle->priority ?></td>
    </tr>
</table>
<br />
<table class="crud">
    <tr>
        <th  colspan="2">Características</th>
    </tr>

    <? foreach($vehicle->Features as $feature): ?>
        <tr>
            <th class="title"><?= $feature->priority ?></th>
            <td><?= $feature->description ?></td>
        </tr>
    <? endforeach; ?>
</table>

<br />

<table class="crud">

    <tr>
        <th  colspan="2">Imagens</th>
    </tr>

    <? foreach($vehicle->Images as $image): ?>
        <tr>
            <th>
                <ul>
                    <li>
                        <label>Imagem</label>
                        <?= $image->Image->filename ?>.png
                    </li>
                    <li>
                        <label>Foto Ilustrativa</label>
                        <?= ($image->illustrative) ? 'Sim' : 'Não' ?>
                    </li>
                    <li>
                        <label>Texto alternativo</label>
                        <?= $image->alt ?>
                    </li>
                    <li>
                        <label>Títuo</label>
                        <?= $image->title ?>
                    </li>
                    <li>
                        <label>Descrição</label>
                        <?= $image->description ?>
                    </li>
                    <li>
                        <label>Ordem</label>
                        <?= $image->priority ?>
                    </li>
                </ul>
            
                <img alt="<?= $image->alt ?>"
                     title="<?= $image->title ?>"
                     src="<?= $this->image($image->Image->filename . '.png','220x220') ?>"
                     />

            </th>
        </tr>
    <? endforeach; ?>

</table>
