<?php

/**
 * Car
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Car extends Base_Car
{

    /**
     * Get the main image
     * @return Doctrine_Record|stdClass
     */
    public function getImage()
    {
        $dql = Doctrine_Query::create()
                ->from('CarImage CI')
                ->leftJoin('CI.Image')
                ->where('car_id = ?', $this->id)
                ->orderBy('priority ASC');
        if ($dql->count()) {
            $image = $dql->fetchOne();
            return $image;
        }

        return false;
    }

    /**
     * pre save rotines.
     */
    public function preSave()
    {
        $this->calculateUrl();
    }

    /**
     * calculates and sets url
     */
    private function calculateUrl()
    {
        $urlParts = array(
            $this->Brand->name,
            $this->model,
            $this->licensePlate,
        );

        $url = Util_String::arrayToUrl($urlParts);

        $this->_set('url', $url);
    }

}