<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Image extends Base_Image
{

    /**
     * Get the edit url for an image
     * @return string
     */
    public function getEditUrl()
    {
        return $this->getCrudControllerUrl('edit/id/' . $this->id);
    }

    /**
     * Get the del url for an image
     * @return string
     */
    public function getDelUrl()
    {
        return $this->getCrudControllerUrl('del/id/' . $this->id);
    }

    /**
     * Get the admin controller for images
     * @param string $append
     * @return string
     */
    public function getCrudControllerUrl($append = '')
    {
        $fc = Zend_Controller_Front::getInstance();
        $base = $fc->getBaseUrl();
        return $base . '/admin/image-upload/' . $append;
    }

}