<?php

/**
 * Vehicle
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Vehicle extends Base_Vehicle
{

    public function setUp()
    {
        parent::setUp();
        $this->hasMutator('price', 'setPrice');
    }

    /**
     * Get the main image
     * @return Doctrine_Record|stdClass
     */
    public function getImage()
    {
        $dql = Doctrine_Query::create()
                ->from('VehicleImage CI')
                ->leftJoin('CI.Image')
                ->where('Vehicle_id = ?', $this->id)
                ->orderBy('priority ASC');
        if ($dql->count()) {
            $image = $dql->fetchOne();
            return $image;
        }

        return false;
    }

    /**
     * pre save rotines.
     */
    public function preSave()
    {
        $this->calculateUrl();
    }

    /**
     * calculates and sets url
     */
    private function calculateUrl()
    {
        $urlParts = array(
            $this->Brand->name,
            $this->model,
            $this->licensePlate,
        );

        $url = Util_String::arrayToUrl($urlParts);

        $this->_set('url', $url);
    }

    /**
     * Get formated price
     * @return string
     */
    public function getPrice()
    {
        $value = $this->_get('price');
        $options = array(
            'format' => 'pt_BR',
            'display' => Zend_Currency::NO_SYMBOL,
        );
        $cur = new Zend_Currency();
        return $cur->toCurrency($value, $options);
    }

    /**
     *
     * @param string $value
     */
    public function setPrice($value)
    {
        $value = str_replace('.', '', $value);
        $value = str_replace(',', '.', $value);
        $this->_set('price', $value);
    }

}