<div class="search top"><?= $this->search ?>
    <div class="total"><?= $this->pagination()->getPager()->getNumResults() ?> registro(s) encontrado(s).</div>
</div>

<?= $this->flash()->render() ?>



<?= $this->pagination()->render() ?>
<table class="crud">
    <tr>
        <th>Arquivo</th>
        <th>Nome do arquivo</th>
        <th>Descricão</th>
        <th><a class="new-register" href="<?= $this->url(array(
            'module'=>'admin',
            'controller' => 'image-upload',
            'action' => 'add'
        ),null,true)?>" >Adicionar</a></th>

    </tr>
    <? foreach($this->registers as $i => $register) : ?>
        <tr class="r<?=($i%2)?>">
            <td>
                <div class="img center bg-white fleft middle" style="width:100px;height:100px">
                    <img src="<?= $this->image($register->filename . '.png','100x100')?>"
                         title="<?= $register->description ?>" alt="<?= $register->description ?>" />
                </div>
            </td>
            <td><?= $register->filename ?></td>
            <td><?= $register->description ?></td>
            <td class="actions">
                <a class="edit" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'image-upload',
                            'action' => 'edit',
                            'id' => $register->id
                        ),null,true)?>" >Editar</a>
                
                <a class="del" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'image-upload',
                            'action' => 'del',
                            'id' => $register->id
                        ),null,true)?>" >Excluir</a>
            </td>
        </tr>

    <? endforeach ?>

</table>
<?= $this->pagination()->render() ?>
