options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8

UserRole:
  tableName: user_role
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    name: string(255)
  relations:
    Users:
      class: User
      foreign: role_id
      local: id
      type: many
      onDelete: RESTRICT

User:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
    email:
      type: string(255)
      unique: true
      notnull: true
    login:
      type: string(50)
      unique: true
      notnull: true
    enabled:
      type: boolean
      notnull: true
      default: false
    password:
      type: string(40)
      notnull: true
    password_recovery_hash:
      type: string(40)
      notnull: false
    password_recovery_expiration_date:
      type: datetime
      notnull: false
    role_id:
      type: integer
      unsigned: true
      notnull: true
    image: string(255)
  actAs: [Timestampable]
  relations:
    Role:
      class: UserRole
      local: role_id
      foreign: id

Brand:
  tableName: brand
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
      notnull: true
    image_id:
      type: integer
      unsigned: true
      notnull: false
    url:
      type: string(255)
      unique: true
      notnull: true
  actAs: [Timestampable]
  relations:
    Vehicles:
      class: Vehicle
      foreign: brand_id
      local: id
      type: many
      onDelete: RESTRICT
    Logo:
      class: Image
      local: image_id
      foreign: id
      onDelete: RESTRICT


VehicleType:
  tableName: vehicle_type
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
      notnull: true
    license:
      type: string(5)
      unique: true
  actAs: [Timestampable]
  relations:
    Vehicles:
      class: Vehicle
      foreign: type_id
      local: id
      type: many
      onDelete: RESTRICT

Fuel:
  tableName: fuel
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    name:
      type: string(255)
      unique: true
      notnull: true
    short:
      type: string(255)
      unique: true
      notnull: true
  actAs: [Timestampable]
  relations:
    Vehicles:
      class: Vehicle
      foreign: fuel_id
      local: id
      type: many
      onDelete: RESTRICT
  
Vehicle:
  tableName: Vehicle
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    model:
      type: string(255)
      unique: true
      notnull: true
    color:
      type: string(255)
      notnull: true
    brand_id:
      type: integer
      notnull: true
      unsigned: true
    fuel_id:
      type: integer
      notnull: true
      unsigned: true
    type_id:
      type: integer
      notnull: true
      unsigned: true
    status_id:
      type: integer
      notnull: true
      unsigned: true
    status_modified_at:
      type: timestamp
    price:
      type: float
      default: 0
    showPrice:
      type: boolean
      default: false
      notnull: true
    year:
      type: integer
      notnull: true
    modelYear:
      type: integer
      notnull: true
    priority:
      type: integer
      default: 0
      notnull: true
    licensePlate:
      type: string(8)
      unique: true
      notnull: true
    url:
      type: string(255)
      unique: true
      notnull: true
  actAs: [Timestampable]
  indexes:
    model:
      fields:
        model: []
  relations:
    Status:
      class: VehicleStatus
      local: status_id
      foreign: id
    Type:
      class: VehicleType
      local: type_id
      foreign: id
    Brand:
      class: Brand
      local: brand_id
      foreign: id
    Fuel:
      class: Fuel
      local: fuel_id
      foreign: id
    Features:
      class: VehicleFeature
      foreign: vehicle_id
      local: id
      type: many
    Images:
      class: VehicleImage
      foreign: vehicle_id
      local: id
      type: many

VehicleFeature:
  tableName: vehicle_feature
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    vehicle_id:
      type: integer
      unsigned: true
      notnull: true
    priority:
      type: integer
      unsigned: true
      notnull: true
    description:
      type: string(255)
      notnull: true
  actAs: [Timestampable]
  relations:
    Vehicle:
      class: Vehicle
      local: vehicle_id
      foreign: id
      onDelete: CASCADE
  indexes:
    vehicle_id_description_uk:
      fields:
        vehicle_id: []
        description: []
      type: unique

VehicleImage:
  tableName: vehicle_image
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    vehicle_id:
      type: integer
      unsigned: true
      notnull: true
    image_id:
      type: integer
      unsigned: true
      notnull: true
    priority:
      type: integer
      unsigned: true
      notnull: true
    illustrative:
      type: boolean
      notnull: true
    priority:
      type: integer
      unsigned: true
      notnull: true
    alt:
      type: string(255)
      notnull: true
    title:
      type: string(255)
      notnull: true
    description:
      type: string(255)
      notnull: true
  actAs: [Timestampable]
  relations:
    Vehicle:
      class: Vehicle
      local: vehicle_id
      foreign: id
      onDelete: CASCADE
    Image:
      class: Image
      local: image_id
      foreign: id
  indexes:
    vehicle_id_image_id:
      fields:
        image_id: []
        vehicle_id: []
      type: unique

VehicleStatus:
  tableName: vehicle_status
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    name:
      type: string(255)
      notnull: true
      unique: ture
  relations:
    Vehicles:
      class: Vehicle
      local: id
      foreign: status_id


Image:
  tableName: image
  columns:
    id:
      type: integer
      primary: true
      unsigned: true
      autoincrement: true
    filename:
      type: string(255)
      unique: true
      notnull: true
    md5:
      type: string(32)
      unique: true
      notnull: true
    description:
      type: string(255)
      notnull: true
  relations:
    VehicleImage:
      class: VehicleImage
      foreign: image_id
      local: id
      type: many
      onDelete: RESTRICT
    Brands:
      class: Brand
      foreign: image_id
      local: id
      type: many
      onDelete: RESTRICT
  actAs: [Timestampable]
  indexes:
    description:
      fields: [description]

