<div class="search top"><?= $this->search ?>
    <div class="total"><?= $this->pagination()->getPager()->getNumResults() ?> registro(s) encontrado(s).</div>
</div>

<?= $this->flash()->render() ?>



<?= $this->pagination()->render() ?>
<table class="crud">
    <tr>
        <th>Foto</th>
        <th>Modelo</th>
        <th>Cor</th>
        <th>Ano/Mod</th>
        <th>Valor</th>
        <th>Marca</th>
        <th>Placa</th>


        <th><a class="new-register" href="<?= $this->url(array(
            'module'=>'admin',
            'controller' => 'car',
            'action' => 'add'
        ),null,true)?>" >Adicionar</a></th>

    </tr>
    <? foreach($this->registers as $i => $register) : ?>
        <tr class="r<?=($i%2)?>">
            <td class="thumb">picture</td>
            <td><?= $register->model ?></td>
            <td><?= $register->color ?></td>
            <td class="right"><?= $register->year ?>/<?= $register->modelYear ?></td>
            <td class="right"><?= $register->price ?></td>
            <td><?= $register->Brand->name ?></td>
            <td class="right"><?= $register->licensePlate ?></td>


            <td class="actions">
                <a class="edit" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'car',
                            'action' => 'edit',
                            'id' => $register->id
                        ),null,true)?>" >Editar</a>
                
                <a class="del" href="<?= $this->url(array(
                            'module'=>'admin',
                            'controller' => 'car',
                            'action' => 'del',
                            'id' => $register->id
                        ),null,true)?>" >Excluir</a>
            </td>
        </tr>

    <? endforeach ?>

</table>
<?= $this->pagination()->render() ?>
