<?php
$controllerName = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$user = Zend_Auth::getInstance()->getIdentity();

?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?= $this->headTitle() ?>
        <?= $this->headMeta()
            ->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
            ->appendHttpEquiv('Content-Language', 'pt_BR') ?>
        <?= $this->headLink() ?>
        <?= $this->headStyle() ?>
        <?= $this->headScript() ?>
    </head>
    <body>
        <div id="container">
            
            <div id="header">
                
            </div>



            <div id="left-menu">
                <ul>
                    <?php foreach ($this->tabs as $label => $controllers ): ?>
                        <?php
                            $resource = 'module-admin-controller-' . $controllers[0];


                        ?>
                        <?php if(App_Acl::canAccess($resource)) : ?>
                        <? $class = (in_array($controllerName, $controllers)) ? 'active' : '' ?>
                            <li class="<?= $class ?>">
                                <a href="<?= $this->url(array(
                                'module' => 'admin',
                                'controller' => $controllers[0],
                                'action' => ''), null, true)
                            ?>"><?= $label ?></a>
                        </li>
                        <?php endif ?>
                    <?php endforeach ?>
                    <li>
                        <a href="<?= $this->baseUrl() ?>/admin/authentication/logout">Sair</a>
                    </li>
                </ul>
            </div>
            <div id="content">
                <?= $this->layout()->content; ?>
            </div>

                <div id="footer"></div>
                    <?= $this->inlineScript() ?>
        </div>
    </body>
</html>